# Generated by Django 4.1.2 on 2022-10-11 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('searchScheme', models.TextField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('searchWords', models.TextField()),
                ('ratingPoints', models.IntegerField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('url', models.URLField()),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonShare',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('lastAccess', models.DateField()),
                ('validUntil', models.DateField()),
                ('name', models.CharField(max_length=128)),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comparison')),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonEntryCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField()),
                ('updated', models.DateField()),
                ('comment', models.TextField()),
                ('additionalCosts', models.DecimalField(decimal_places=2, max_digits=8)),
                ('comparisonAttribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comparisonattribute')),
                ('comparisonEntry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.comparisonentry')),
            ],
        ),
    ]
